### ISSUE TITLE
Support multiple embedding models

### ISSUE THREAD

**Issue by zmacks** [whylabs/langkit#120]
The [Universal Sentence Encoder](https://ai.googleblog.com/2018/05/advances-in-semantic-textual-similarity.html) model is a multipurpose sentence embeddings model for semantic similarity.

> The aim is to provide a single encoder that can support as wide a variety of applications as possible, including paraphrase detection, relatedness, clustering and custom text classification.

I'd love to see the model swappable/configurable wherever embeddings are generated.

**Comment by jamie256** [comment]
We have the first part of this request in PR, covering the prompt/response similarity score and themes metric to use a swappable embeddings encode method. Great suggestion, thanks for filing the request @zmacks !
