### ISSUE TITLE
Original data

### ISSUE THREAD

**Issue by iazdan** [whylabs/langkit#223]
Is there a way to share the original data that is used for injection, and other tasks? 

Thanks!

**Comment by FelipeAdachi** [comment]
Hi @iazdan,

The injections module doesn't support access to the original data, just the embeddings.

However, the themes module uses the same approach, though with a much smaller set of prompt injection examples, which is available on langkit in [themes.json](https://github.com/whylabs/langkit/blob/main/langkit/themes.json). You can also provide your own set of examples to be used with the module.
