### ISSUE TITLE
Possible merge issue with 0.0.31 release

### ISSUE THREAD

**Issue by jonbaiernx** [whylabs/langkit#300]
The example on this page appears to want version 0.0.31 to use local models. 
[https://github.com/whylabs/langkit/blob/main/langkit/examples/Local_Models.ipynb](https://github.com/whylabs/langkit/blob/main/langkit/examples/Local_Models.ipynb)

However, it looks like the code to make this happen is only in the main branch and not in the 0.0.31 release. When trying to run the example with latest pip install I get the old error about an unrecognized model.

**Comment by jamie256** [comment]
You are absolutely right, thanks for filing the issue @jonbaiernx and bringing this to our attention. We just released 0.0.32 which I believe resolves this issue (along with an updated pip install command in the example https://github.com/whylabs/langkit/pull/308)
