### ISSUE TITLE
Deploying in heroku - python flask server

### ISSUE THREAD

**Issue by sarulnat** [whylabs/langkit#48]
Hi all, thanks for your work on the langkit integration. it is working for me on localhost. however when i deploy to heroku i get an error for slug size too large at 2.4 gb (see attached screenshot).

I'm using:
langchain==0.0.187
langkit==0.0.1b4
I've uninstalled langkit and it deploys fine. is anyone else using heroku or running into this issue?
thanks!

here are the new modules added from langkit (from my requirements.txt)
datasets==2.12.0
dill==0.3.6
filelock==3.12.0
fsspec==2023.5.0
huggingface-hub==0.15.1
joblib==1.2.0
langkit==0.0.1b4
mpmath==1.3.0
multiprocess==0.70.14
networkx==3.1
nltk==3.8.1
pandas==2.0.2
protobuf==4.23.2
pyarrow==12.0.0
pyphen==0.14.0
responses==0.18.0
scikit-learn==1.2.2
scipy==1.10.1
sentence-transformers==2.2.2
sentencepiece==0.1.99
sympy==1.12
textstat==0.7.3
threadpoolctl==3.1.0
tokenizers==0.13.3
torch==2.0.1
torchvision==0.15.2
transformers==4.29.2
tzdata==2023.3
whylabs-client==0.5.1
whylogs==1.1.43.dev0
whylogs-sketching==3.4.1.dev3
xxhash==3.2.0
In my app.py file (python flask server) i am using 'from langchain.callbacks import WhyLabsCallbackHandler'

Response from Andre (WhyLabs Team) on Slack:
I’m assuming this is because of the dependencies we’re pulling in for the library, at the moment we don’t have any extras defined to make the distribution smaller which is probably why you’re seeing the additional space, can you make an issue on the repo? Also any code contributions are welcome :pray:  https://github.com/whylabs/langkit/issues

**Comment by jamie256** [comment]
we've made most of the larger packages now optional in LangKit, so the install from LangChain to LangKit will only pull in a minimal set of dependencies. Can you see if this works for you with our 0.0.1 build of LangKit?

**Comment by andrewelizondo** [comment]
@sarulnat closing this out since as of 0.0.1 the base install should be small enough to run in heroku
